version: '3.0'

services:
  webserver:
    image: ylked/historiska-laravel
    container_name: historiska-api-server
    ports:
      - 8000:8000
    volumes:
      - ./historiska-api-server/:/files
      - ./server-log:/var/log/apache2
    working_dir: /files

  vue:
    image: ylked/historiska-node
    container_name: historiska-vue-front
    ports:
      - 3000:3000
      - 80:80
    volumes:
      - ./historiska-vue-front/:/files
    working_dir: /files

  db:
    image: mariadb
    container_name: historiska-database
    volumes:
      - ./db-data:/var/lib/mysql
    ports:
      - 3306:3306

    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "default"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "pass"

  adminer:
    image: adminer
    container_name: historiska-adminer

    ports:
      - 8080:8080

